### ISSUE TITLE
Coredump message needs more info.

### ISSUE THREAD

**Issue by FeelyChau** [yodaos-project/edge-monitor#5]
Currently the coredump info includes bin name, coredump file and device id, but the parameters and device version info are necessary for debugging.

**Comment by yorkie** [comment]
How about viewing the stack from these dumps directly? We might only need the OS version and a complete environment.

**Comment by FeelyChau** [comment]
> How about viewing the stack from these dumps directly? We might only need the OS version and a complete environment.

Further, we can save the debugging environment and directly get the stack information in the debugging environment when the coredump appears, then we can view the stack from webpages.

**Comment by lolBig** [comment]
> How about viewing the stack from these dumps directly? We might only need the OS version and a complete environment.

How about save the staging directory after every image built in CI? thus we can view the stacks directly in the website after coredump uploaded.

**Comment by yorkie** [comment]
> How about save the staging directory after every image built in CI? thus we can view the stacks directly in the website after coredump uploaded.

This is what I meant, the followings should be included in release:

- images(ota and flush)
- development kit and cross-compile environment
- online debug environment
